# Generated by Django 5.1.3 on 2024-12-18 00:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_feedback_userfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedback',
            new_name='Feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedback_text',
        ),
    ]
