# Generated by Django 5.1.3 on 2025-01-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_userfeedback_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='feedback_message',
        ),
    ]
