# Generated by Django 5.1.3 on 2024-12-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_incidentreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='received', max_length=50),
        ),
    ]
