# Generated by Django 5.1.3 on 2024-12-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_incidentreport_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidentReport',
        ),
    ]
