# Generated by Django 5.1.3 on 2025-01-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incidentreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Traffic Accident', 'Traffic Accident'), ('Unsafe Condition', 'Unsafe Condition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='received', max_length=50),
        ),
    ]
