# Generated by Django 5.1.3 on 2025-01-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incidentreport_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Received', max_length=50),
        ),
    ]
