# Generated by Django 5.1.3 on 2025-01-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_incident_notification_target_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='verb',
            new_name='message',
        ),
    ]
