# Generated by Django 5.1.3 on 2025-01-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_verb_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target',
            new_name='incident',
        ),
    ]
