# Generated by Django 5.1.3 on 2025-01-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_recipient_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
    ]
