# Generated by Django 5.1.3 on 2025-01-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rename_user_notification_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
    ]
