# Generated by Django 5.1.3 on 2025-01-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target',
            new_name='receiver',
        ),
    ]
